package com.mavenMVC.entity;
// Generated 2017-12-10 21:51:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name="activity"
    ,catalog="farm"
)
public class Activity  implements java.io.Serializable {


     private Long activityId;
     private String activityTitle;
     private String activityContent;
     private Integer activityPrice;
     private String activityImage;
     private Integer activityStatus;
     private Integer activityNum;
     private Long createTime;
     private Long lastModTime;

    public Activity() {
    }

    public Activity(String activityTitle, String activityContent, Integer activityPrice, String activityImage, Integer activityStatus, Integer activityNum, Long createTime, Long lastModTime) {
       this.activityTitle = activityTitle;
       this.activityContent = activityContent;
       this.activityPrice = activityPrice;
       this.activityImage = activityImage;
       this.activityStatus = activityStatus;
       this.activityNum = activityNum;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ACTIVITY_ID", unique=true, nullable=false)
    public Long getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }
    
    @Column(name="ACTIVITY_TITLE", length=65535)
    public String getActivityTitle() {
        return this.activityTitle;
    }
    
    public void setActivityTitle(String activityTitle) {
        this.activityTitle = activityTitle;
    }
    
    @Column(name="ACTIVITY_CONTENT", length=65535)
    public String getActivityContent() {
        return this.activityContent;
    }
    
    public void setActivityContent(String activityContent) {
        this.activityContent = activityContent;
    }
    
    @Column(name="ACTIVITY_PRICE")
    public Integer getActivityPrice() {
        return this.activityPrice;
    }
    
    public void setActivityPrice(Integer activityPrice) {
        this.activityPrice = activityPrice;
    }
    
    @Column(name="ACTIVITY_IMAGE", length=1022)
    public String getActivityImage() {
        return this.activityImage;
    }
    
    public void setActivityImage(String activityImage) {
        this.activityImage = activityImage;
    }
    
    @Column(name="ACTIVITY_STATUS")
    public Integer getActivityStatus() {
        return this.activityStatus;
    }
    
    public void setActivityStatus(Integer activityStatus) {
        this.activityStatus = activityStatus;
    }
    
    @Column(name="ACTIVITY_NUM")
    public Integer getActivityNum() {
        return this.activityNum;
    }
    
    public void setActivityNum(Integer activityNum) {
        this.activityNum = activityNum;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }




}


