package com.mavenMVC.entity;
// Generated 2017-12-10 21:51:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
    ,catalog="farm"
)
public class Address  implements java.io.Serializable {


     private Long addressId;
     private Long userId;
     private String addressName;
     private String addressCellphone;
     private String addressMsg;
     private String addressDetail;
     private Integer addressDefault;
     private Long createTime;
     private Long lastModTime;

    public Address() {
    }

    public Address(Long userId, String addressName, String addressCellphone, String addressMsg, String addressDetail, Integer addressDefault, Long createTime, Long lastModTime) {
       this.userId = userId;
       this.addressName = addressName;
       this.addressCellphone = addressCellphone;
       this.addressMsg = addressMsg;
       this.addressDetail = addressDetail;
       this.addressDefault = addressDefault;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ADDRESS_ID", unique=true, nullable=false)
    public Long getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }
    
    @Column(name="USER_ID")
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    @Column(name="ADDRESS_NAME", length=45)
    public String getAddressName() {
        return this.addressName;
    }
    
    public void setAddressName(String addressName) {
        this.addressName = addressName;
    }
    
    @Column(name="ADDRESS_CELLPHONE", length=45)
    public String getAddressCellphone() {
        return this.addressCellphone;
    }
    
    public void setAddressCellphone(String addressCellphone) {
        this.addressCellphone = addressCellphone;
    }
    
    @Column(name="ADDRESS_MSG", length=65535)
    public String getAddressMsg() {
        return this.addressMsg;
    }
    
    public void setAddressMsg(String addressMsg) {
        this.addressMsg = addressMsg;
    }
    
    @Column(name="ADDRESS_DETAIL", length=65535)
    public String getAddressDetail() {
        return this.addressDetail;
    }
    
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail;
    }
    
    @Column(name="ADDRESS_DEFAULT")
    public Integer getAddressDefault() {
        return this.addressDefault;
    }
    
    public void setAddressDefault(Integer addressDefault) {
        this.addressDefault = addressDefault;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


    /**
     * Property name constant for {@code createTime}.
     */
    public static final String PROPERTYNAME_CREATE_TIME = "createTime";
    /**
     * Property name constant for {@code addressMsg}.
     */
    public static final String PROPERTYNAME_ADDRESS_MSG = "addressMsg";
    /**
     * Property name constant for {@code addressCellphone}.
     */
    public static final String PROPERTYNAME_ADDRESS_CELLPHONE = "addressCellphone";
    /**
     * Property name constant for {@code addressDefault}.
     */
    public static final String PROPERTYNAME_ADDRESS_DEFAULT = "addressDefault";
    /**
     * Property name constant for {@code lastModTime}.
     */
    public static final String PROPERTYNAME_LAST_MOD_TIME = "lastModTime";
    /**
     * Property name constant for {@code addressName}.
     */
    public static final String PROPERTYNAME_ADDRESS_NAME = "addressName";
    /**
     * Property name constant for {@code addressDetail}.
     */
    public static final String PROPERTYNAME_ADDRESS_DETAIL = "addressDetail";
    /**
     * Property name constant for {@code userId}.
     */
    public static final String PROPERTYNAME_USER_ID = "userId";
    /**
     * Property name constant for {@code addressId}.
     */
    public static final String PROPERTYNAME_ADDRESS_ID = "addressId";
}


