package com.mavenMVC.entity;
// Generated 2017-12-10 21:51:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Adminrole generated by hbm2java
 */
@Entity
@Table(name="adminrole"
    ,catalog="farm"
)
public class Adminrole  implements java.io.Serializable {


     private Long adminRoleId;
     private Long adminRoleUid;
     private Long adminRoleRid;
     private Long createTime;
     private Long lastModTime;

    public Adminrole() {
    }

    public Adminrole(Long adminRoleUid, Long adminRoleRid, Long createTime, Long lastModTime) {
       this.adminRoleUid = adminRoleUid;
       this.adminRoleRid = adminRoleRid;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ADMIN_ROLE_ID", unique=true, nullable=false)
    public Long getAdminRoleId() {
        return this.adminRoleId;
    }
    
    public void setAdminRoleId(Long adminRoleId) {
        this.adminRoleId = adminRoleId;
    }
    
    @Column(name="ADMIN_ROLE_UID")
    public Long getAdminRoleUid() {
        return this.adminRoleUid;
    }
    
    public void setAdminRoleUid(Long adminRoleUid) {
        this.adminRoleUid = adminRoleUid;
    }
    
    @Column(name="ADMIN_ROLE_RID")
    public Long getAdminRoleRid() {
        return this.adminRoleRid;
    }
    
    public void setAdminRoleRid(Long adminRoleRid) {
        this.adminRoleRid = adminRoleRid;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


    /**
     * Property name constant for {@code adminRoleId}.
     */
    public static final String PROPERTYNAME_ADMIN_ROLE_ID = "adminRoleId";
    /**
     * Property name constant for {@code createTime}.
     */
    public static final String PROPERTYNAME_CREATE_TIME = "createTime";
    /**
     * Property name constant for {@code adminRoleUid}.
     */
    public static final String PROPERTYNAME_ADMIN_ROLE_UID = "adminRoleUid";
    /**
     * Property name constant for {@code lastModTime}.
     */
    public static final String PROPERTYNAME_LAST_MOD_TIME = "lastModTime";
    /**
     * Property name constant for {@code adminRoleRid}.
     */
    public static final String PROPERTYNAME_ADMIN_ROLE_RID = "adminRoleRid";
}


