package com.mavenMVC.entity;
// Generated 2017-12-10 21:51:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="farm"
)
public class Admin  implements java.io.Serializable {


     private Long adminId;
     private String adminPassword;
     private String adminName;
     private Integer adminStatus;
     private Integer adminType;
     private Long createTime;
     private Long lastModTime;

    public Admin() {
    }

    public Admin(String adminPassword, String adminName, Integer adminStatus, Integer adminType, Long createTime, Long lastModTime) {
       this.adminPassword = adminPassword;
       this.adminName = adminName;
       this.adminStatus = adminStatus;
       this.adminType = adminType;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ADMIN_ID", unique=true, nullable=false)
    public Long getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }
    
    @Column(name="ADMIN_PASSWORD", length=45)
    public String getAdminPassword() {
        return this.adminPassword;
    }
    
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }
    
    @Column(name="ADMIN_NAME", length=45)
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }
    
    @Column(name="ADMIN_STATUS")
    public Integer getAdminStatus() {
        return this.adminStatus;
    }
    
    public void setAdminStatus(Integer adminStatus) {
        this.adminStatus = adminStatus;
    }
    
    @Column(name="ADMIN_TYPE")
    public Integer getAdminType() {
        return this.adminType;
    }
    
    public void setAdminType(Integer adminType) {
        this.adminType = adminType;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }




}


