package com.mavenMVC.entity;
// Generated 2017-12-10 21:51:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Cartcommodity generated by hbm2java
 */
@Entity
@Table(name="cartcommodity"
    ,catalog="farm"
)
public class Cartcommodity  implements java.io.Serializable {


     private Long cartCommodityId;
     private Long userId;
     private Long commodityId;
     private Integer commodityNum;
     private Long createTime;
     private Long lastModTime;

    public Cartcommodity() {
    }

    public Cartcommodity(Long userId, Long commodityId, Integer commodityNum, Long createTime, Long lastModTime) {
       this.userId = userId;
       this.commodityId = commodityId;
       this.commodityNum = commodityNum;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="CART_COMMODITY_ID", unique=true, nullable=false)
    public Long getCartCommodityId() {
        return this.cartCommodityId;
    }
    
    public void setCartCommodityId(Long cartCommodityId) {
        this.cartCommodityId = cartCommodityId;
    }
    
    @Column(name="USER_ID")
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    @Column(name="COMMODITY_ID")
    public Long getCommodityId() {
        return this.commodityId;
    }
    
    public void setCommodityId(Long commodityId) {
        this.commodityId = commodityId;
    }
    
    @Column(name="COMMODITY_NUM")
    public Integer getCommodityNum() {
        return this.commodityNum;
    }
    
    public void setCommodityNum(Integer commodityNum) {
        this.commodityNum = commodityNum;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


    /**
     * Property name constant for {@code lastModTime}.
     */
    public static final String PROPERTYNAME_LAST_MOD_TIME = "lastModTime";
    /**
     * Property name constant for {@code createTime}.
     */
    public static final String PROPERTYNAME_CREATE_TIME = "createTime";
    /**
     * Property name constant for {@code commodityNum}.
     */
    public static final String PROPERTYNAME_COMMODITY_NUM = "commodityNum";
    /**
     * Property name constant for {@code userId}.
     */
    public static final String PROPERTYNAME_USER_ID = "userId";
    /**
     * Property name constant for {@code commodityId}.
     */
    public static final String PROPERTYNAME_COMMODITY_ID = "commodityId";
    /**
     * Property name constant for {@code cartCommodityId}.
     */
    public static final String PROPERTYNAME_CART_COMMODITY_ID = "cartCommodityId";
}


