package com.mavenMVC.entity;
// Generated 2018-1-17 14:23:57 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Commoditycategory generated by hbm2java
 */
@Entity
@Table(name="commoditycategory"
    ,catalog="farm"
)
public class Commoditycategory implements java.io.Serializable {


     private Long commodityCategoryId;
     private String commodityCategoryName;
     private Long createTime;
     private Long lastModTime;

    public Commoditycategory() {
    }

    public Commoditycategory(String commodityCategoryName, Long createTime, Long lastModTime) {
       this.commodityCategoryName = commodityCategoryName;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="COMMODITY_CATEGORY_ID", unique=true, nullable=false)
    public Long getCommodityCategoryId() {
        return this.commodityCategoryId;
    }
    
    public void setCommodityCategoryId(Long commodityCategoryId) {
        this.commodityCategoryId = commodityCategoryId;
    }
    
    @Column(name="COMMODITY_CATEGORY_NAME")
    public String getCommodityCategoryName() {
        return this.commodityCategoryName;
    }
    
    public void setCommodityCategoryName(String commodityCategoryName) {
        this.commodityCategoryName = commodityCategoryName;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


    /**
     * Property name constant for {@code commodityCategoryName}.
     */
    public static final String PROPERTYNAME_COMMODITY_CATEGORY_NAME = "commodityCategoryName";
    /**
     * Property name constant for {@code createTime}.
     */
    public static final String PROPERTYNAME_CREATE_TIME = "createTime";
    /**
     * Property name constant for {@code commodityCategoryId}.
     */
    public static final String PROPERTYNAME_COMMODITY_CATEGORY_ID = "commodityCategoryId";
    /**
     * Property name constant for {@code lastModTime}.
     */
    public static final String PROPERTYNAME_LAST_MOD_TIME = "lastModTime";
}


