package com.mavenMVC.entity;
// Generated 2017-12-10 21:51:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Commodity generated by hbm2java
 */
@Entity
@Table(name="commodity"
    ,catalog="farm"
)
public class Commodity  implements java.io.Serializable {

     private Long commodityId;
     private Integer commodityPrice;
    private String commodityName;
     private String commodityDetail;
     private String commodityImages;
     private Integer commodityStatus;
     private Integer commodityType;
     private Long commodityCategory;
     private Integer commoditySaleNum;
     private Long createTime;
     private Long lastModTime;

    public Commodity() {
    }

    public Commodity(Integer commodityPrice, String commodityName, String commodityDetail, String commodityImages, Integer commodityStatus, Integer commodityType, Long commodityCategory, Integer commoditySaleNum, Long createTime, Long lastModTime) {
       this.commodityPrice = commodityPrice;
       this.commodityName = commodityName;
       this.commodityDetail = commodityDetail;
       this.commodityImages = commodityImages;
       this.commodityStatus = commodityStatus;
       this.commodityType = commodityType;
       this.commodityCategory = commodityCategory;
       this.commoditySaleNum = commoditySaleNum;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="COMMODITY_ID", unique=true, nullable=false)
    public Long getCommodityId() {
        return this.commodityId;
    }
    
    public void setCommodityId(Long commodityId) {
        this.commodityId = commodityId;
    }
    
    @Column(name="COMMODITY_PRICE")
    public Integer getCommodityPrice() {
        return this.commodityPrice;
    }
    
    public void setCommodityPrice(Integer commodityPrice) {
        this.commodityPrice = commodityPrice;
    }

    @Column(name="COMMODITY_NAME", length=45)
    public String getCommodityName() {
        return commodityName;
    }

    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName;
    }

    @Column(name="COMMODITY_DETAIL", length=65535)
    public String getCommodityDetail() {
        return this.commodityDetail;
    }
    
    public void setCommodityDetail(String commodityDetail) {
        this.commodityDetail = commodityDetail;
    }
    
    @Column(name="COMMODITY_IMAGES", length=65535)
    public String getCommodityImages() {
        return this.commodityImages;
    }
    
    public void setCommodityImages(String commodityImages) {
        this.commodityImages = commodityImages;
    }
    
    @Column(name="COMMODITY_STATUS")
    public Integer getCommodityStatus() {
        return this.commodityStatus;
    }
    
    public void setCommodityStatus(Integer commodityStatus) {
        this.commodityStatus = commodityStatus;
    }
    
    @Column(name="COMMODITY_TYPE")
    public Integer getCommodityType() {
        return this.commodityType;
    }
    
    public void setCommodityType(Integer commodityType) {
        this.commodityType = commodityType;
    }
    
    @Column(name="COMMODITY_CATEGORY")
    public Long getCommodityCategory() {
        return this.commodityCategory;
    }
    
    public void setCommodityCategory(Long commodityCategory) {
        this.commodityCategory = commodityCategory;
    }
    
    @Column(name="COMMODITY_SALE_NUM")
    public Integer getCommoditySaleNum() {
        return this.commoditySaleNum;
    }
    
    public void setCommoditySaleNum(Integer commoditySaleNum) {
        this.commoditySaleNum = commoditySaleNum;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


    /**
     * Property name constant for {@code createTime}.
     */
    public static final String PROPERTYNAME_CREATE_TIME = "createTime";
    /**
     * Property name constant for {@code commodityId}.
     */
    public static final String PROPERTYNAME_COMMODITY_ID = "commodityId";
    /**
     * Property name constant for {@code commoditySaleNum}.
     */
    public static final String PROPERTYNAME_COMMODITY_SALE_NUM = "commoditySaleNum";
    /**
     * Property name constant for {@code commodityCategory}.
     */
    public static final String PROPERTYNAME_COMMODITY_CATEGORY = "commodityCategory";
    /**
     * Property name constant for {@code commodityDetail}.
     */
    public static final String PROPERTYNAME_COMMODITY_DETAIL = "commodityDetail";
    /**
     * Property name constant for {@code lastModTime}.
     */
    public static final String PROPERTYNAME_LAST_MOD_TIME = "lastModTime";
    /**
     * Property name constant for {@code commodityStatus}.
     */
    public static final String PROPERTYNAME_COMMODITY_STATUS = "commodityStatus";
    /**
     * Property name constant for {@code commodityImages}.
     */
    public static final String PROPERTYNAME_COMMODITY_IMAGES = "commodityImages";
    /**
     * Property name constant for {@code commodityPrice}.
     */
    public static final String PROPERTYNAME_COMMODITY_PRICE = "commodityPrice";
    /**
     * Property name constant for {@code commodityType}.
     */
    public static final String PROPERTYNAME_COMMODITY_TYPE = "commodityType";
    /**
     * Property name constant for {@code commodityName}.
     */
    public static final String PROPERTYNAME_COMMODITY_NAME = "commodityName";
}


