package com.mavenMVC.entity;
// Generated 2017-12-10 22:08:10 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Dinnertable generated by hbm2java
 */
@Entity
@Table(name="dinnertable"
    ,catalog="farm"
)
public class Dinnertable implements java.io.Serializable {


     private Long tableId;
     private Long tableType;
     private String tableName;
     private Long createTime;
     private Long lastModTime;

    public Dinnertable() {
    }

    public Dinnertable(Long tableType, String tableName, Long createTime, Long lastModTime) {
       this.tableType = tableType;
       this.tableName = tableName;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="TABLE_ID", unique=true, nullable=false)
    public Long getTableId() {
        return this.tableId;
    }
    
    public void setTableId(Long tableId) {
        this.tableId = tableId;
    }
    
    @Column(name="TABLE_TYPE")
    public Long getTableType() {
        return this.tableType;
    }
    
    public void setTableType(Long tableType) {
        this.tableType = tableType;
    }
    
    @Column(name="TABLE_NAME", length=45)
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


    /**
     * Property name constant for {@code tableId}.
     */
    public static final String PROPERTYNAME_TABLE_ID = "tableId";
    /**
     * Property name constant for {@code createTime}.
     */
    public static final String PROPERTYNAME_CREATE_TIME = "createTime";
    /**
     * Property name constant for {@code tableType}.
     */
    public static final String PROPERTYNAME_TABLE_TYPE = "tableType";
    /**
     * Property name constant for {@code lastModTime}.
     */
    public static final String PROPERTYNAME_LAST_MOD_TIME = "lastModTime";
    /**
     * Property name constant for {@code tableName}.
     */
    public static final String PROPERTYNAME_TABLE_NAME = "tableName";
}


