package com.mavenMVC.entity;
// Generated 2018-1-4 22:49:46 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Dishtype generated by hbm2java
 */
@Entity
@Table(name="dishtype"
    ,catalog="farm"
)
public class Dishtype implements java.io.Serializable {


     private Long dishTypeId;
     private String dishTypeName;
     private Long createTime;
     private Long lastModTime;

    public Dishtype() {
    }

    public Dishtype(String dishTypeName, Long createTime, Long lastModTime) {
       this.dishTypeName = dishTypeName;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="DISH_TYPE_ID", unique=true, nullable=false)
    public Long getDishTypeId() {
        return this.dishTypeId;
    }
    
    public void setDishTypeId(Long dishTypeId) {
        this.dishTypeId = dishTypeId;
    }
    
    @Column(name="DISH_TYPE_NAME", length=20)
    public String getDishTypeName() {
        return this.dishTypeName;
    }
    
    public void setDishTypeName(String dishTypeName) {
        this.dishTypeName = dishTypeName;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


    /**
     * Property name constant for {@code createTime}.
     */
    public static final String PROPERTYNAME_CREATE_TIME = "createTime";
    /**
     * Property name constant for {@code dishTypeId}.
     */
    public static final String PROPERTYNAME_DISH_TYPE_ID = "dishTypeId";
    /**
     * Property name constant for {@code dishTypeName}.
     */
    public static final String PROPERTYNAME_DISH_TYPE_NAME = "dishTypeName";
    /**
     * Property name constant for {@code lastModTime}.
     */
    public static final String PROPERTYNAME_LAST_MOD_TIME = "lastModTime";
}


