package com.mavenMVC.entity;
// Generated 2017-12-10 21:51:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Dishorder generated by hbm2java
 */
@Entity
@Table(name="dishorder"
    ,catalog="farm"
)
public class Dishorder  implements java.io.Serializable {


     private Long dishOrderId;
     private Long userId;
     private Long tableId;
     private String dishIds;
     private Integer dishOrderStatus;
     private Integer dishOrderPrice;
     private Long createTime;
     private Long lastModTime;

    public Dishorder() {
    }

    public Dishorder(Long userId, Long tableId, String dishIds, Integer dishOrderStatus, Integer dishOrderPrice, Long createTime, Long lastModTime) {
       this.userId = userId;
       this.tableId = tableId;
       this.dishIds = dishIds;
       this.dishOrderStatus = dishOrderStatus;
       this.dishOrderPrice = dishOrderPrice;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="DISH_ORDER_ID", unique=true, nullable=false)
    public Long getDishOrderId() {
        return this.dishOrderId;
    }
    
    public void setDishOrderId(Long dishOrderId) {
        this.dishOrderId = dishOrderId;
    }
    
    @Column(name="USER_ID")
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    @Column(name="TABLE_ID")
    public Long getTableId() {
        return this.tableId;
    }
    
    public void setTableId(Long tableId) {
        this.tableId = tableId;
    }
    
    @Column(name="DISH_IDS", length=65535)
    public String getDishIds() {
        return this.dishIds;
    }
    
    public void setDishIds(String dishIds) {
        this.dishIds = dishIds;
    }
    
    @Column(name="DISH_ORDER_STATUS")
    public Integer getDishOrderStatus() {
        return this.dishOrderStatus;
    }
    
    public void setDishOrderStatus(Integer dishOrderStatus) {
        this.dishOrderStatus = dishOrderStatus;
    }
    
    @Column(name="DISH_ORDER_PRICE")
    public Integer getDishOrderPrice() {
        return this.dishOrderPrice;
    }
    
    public void setDishOrderPrice(Integer dishOrderPrice) {
        this.dishOrderPrice = dishOrderPrice;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


    /**
     * Property name constant for {@code createTime}.
     */
    public static final String PROPERTYNAME_CREATE_TIME = "createTime";
    /**
     * Property name constant for {@code tableId}.
     */
    public static final String PROPERTYNAME_TABLE_ID = "tableId";
    /**
     * Property name constant for {@code lastModTime}.
     */
    public static final String PROPERTYNAME_LAST_MOD_TIME = "lastModTime";
    /**
     * Property name constant for {@code userId}.
     */
    public static final String PROPERTYNAME_USER_ID = "userId";
    /**
     * Property name constant for {@code dishOrderId}.
     */
    public static final String PROPERTYNAME_DISH_ORDER_ID = "dishOrderId";
    /**
     * Property name constant for {@code dishOrderStatus}.
     */
    public static final String PROPERTYNAME_DISH_ORDER_STATUS = "dishOrderStatus";
    /**
     * Property name constant for {@code dishIds}.
     */
    public static final String PROPERTYNAME_DISH_IDS = "dishIds";
    /**
     * Property name constant for {@code dishOrderPrice}.
     */
    public static final String PROPERTYNAME_DISH_ORDER_PRICE = "dishOrderPrice";
}


