package com.mavenMVC.entity;
// Generated 2017-12-10 21:51:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Queue generated by hbm2java
 */
@Entity
@Table(name="queue"
    ,catalog="farm"
)
public class Queue  implements java.io.Serializable {


     private Long queueId;
     private Long userId;
     private Integer queueCalled;
     private Long queueTabelType;
     private Long createTime;
     private Long lastModTime;

    public Queue() {
    }

    public Queue(Long userId, Integer queueCalled, Long queueTabelType, Long createTime, Long lastModTime) {
       this.userId = userId;
       this.queueCalled = queueCalled;
       this.queueTabelType = queueTabelType;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="QUEUE_ID", unique=true, nullable=false)
    public Long getQueueId() {
        return this.queueId;
    }
    
    public void setQueueId(Long queueId) {
        this.queueId = queueId;
    }
    
    @Column(name="USER_ID")
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    @Column(name="QUEUE_CALLED")
    public Integer getQueueCalled() {
        return this.queueCalled;
    }
    
    public void setQueueCalled(Integer queueCalled) {
        this.queueCalled = queueCalled;
    }
    
    @Column(name="QUEUE_TABEL_TYPE")
    public Long getQueueTabelType() {
        return this.queueTabelType;
    }
    
    public void setQueueTabelType(Long queueTabelType) {
        this.queueTabelType = queueTabelType;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }


    /**
     * Property name constant for {@code userId}.
     */
    public static final String PROPERTYNAME_USER_ID = "userId";
    /**
     * Property name constant for {@code queueCalled}.
     */
    public static final String PROPERTYNAME_QUEUE_CALLED = "queueCalled";
    /**
     * Property name constant for {@code queueTabelType}.
     */
    public static final String PROPERTYNAME_QUEUE_TABEL_TYPE = "queueTabelType";
    /**
     * Property name constant for {@code queueId}.
     */
    public static final String PROPERTYNAME_QUEUE_ID = "queueId";
    /**
     * Property name constant for {@code lastModTime}.
     */
    public static final String PROPERTYNAME_LAST_MOD_TIME = "lastModTime";
    /**
     * Property name constant for {@code createTime}.
     */
    public static final String PROPERTYNAME_CREATE_TIME = "createTime";
}


