package com.mavenMVC.entity;
// Generated 2018-1-17 19:33:43 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Tabletype generated by hbm2java
 */
@Entity
@Table(name="tabletype"
    ,catalog="farm"
)
public class Tabletype implements java.io.Serializable {


     private Long tableTypeId;
     private String tableTypeName;
     private Integer tableMaxNum;
     private Integer tableMinNum;
     private String tableDescribe;
     private String tableTimeScale;
     private String tableImage;
     private Long createTime;
     private Long lastModTime;

    public Tabletype() {
    }

    public Tabletype(String tableTypeName, Integer tableMaxNum, Integer tableMinNum, String tableDescribe, String tableTimeScale, String tableImage, Long createTime, Long lastModTime) {
       this.tableTypeName = tableTypeName;
       this.tableMaxNum = tableMaxNum;
       this.tableMinNum = tableMinNum;
       this.tableDescribe = tableDescribe;
       this.tableTimeScale = tableTimeScale;
       this.tableImage = tableImage;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="TABLE_TYPE_ID", unique=true, nullable=false)
    public Long getTableTypeId() {
        return this.tableTypeId;
    }
    
    public void setTableTypeId(Long tableTypeId) {
        this.tableTypeId = tableTypeId;
    }
    
    @Column(name="TABLE_TYPE_NAME", length=45)
    public String getTableTypeName() {
        return this.tableTypeName;
    }
    
    public void setTableTypeName(String tableTypeName) {
        this.tableTypeName = tableTypeName;
    }
    
    @Column(name="TABLE_MAX_NUM")
    public Integer getTableMaxNum() {
        return this.tableMaxNum;
    }
    
    public void setTableMaxNum(Integer tableMaxNum) {
        this.tableMaxNum = tableMaxNum;
    }
    
    @Column(name="TABLE_MIN_NUM")
    public Integer getTableMinNum() {
        return this.tableMinNum;
    }
    
    public void setTableMinNum(Integer tableMinNum) {
        this.tableMinNum = tableMinNum;
    }
    
    @Column(name="TABLE_DESCRIBE", length=65535)
    public String getTableDescribe() {
        return this.tableDescribe;
    }
    
    public void setTableDescribe(String tableDescribe) {
        this.tableDescribe = tableDescribe;
    }
    
    @Column(name="TABLE_TIME_SCALE")
    public String getTableTimeScale() {
        return this.tableTimeScale;
    }
    
    public void setTableTimeScale(String tableTimeScale) {
        this.tableTimeScale = tableTimeScale;
    }
    
    @Column(name="TABLE_IMAGE")
    public String getTableImage() {
        return this.tableImage;
    }
    
    public void setTableImage(String tableImage) {
        this.tableImage = tableImage;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }

    /**
     * Property name constant for {@code tableMinNum}.
     */
    public static final String PROPERTYNAME_TABLE_MIN_NUM = "tableMinNum";
    /**
     * Property name constant for {@code createTime}.
     */
    public static final String PROPERTYNAME_CREATE_TIME = "createTime";
    /**
     * Property name constant for {@code tableDescribe}.
     */
    public static final String PROPERTYNAME_TABLE_DESCRIBE = "tableDescribe";
    /**
     * Property name constant for {@code tableTimeScale}.
     */
    public static final String PROPERTYNAME_TABLE_TIME_SCALE = "tableTimeScale";
    /**
     * Property name constant for {@code tableTypeId}.
     */
    public static final String PROPERTYNAME_TABLE_TYPE_ID = "tableTypeId";
    /**
     * Property name constant for {@code tableImage}.
     */
    public static final String PROPERTYNAME_TABLE_IMAGE = "tableImage";
    /**
     * Property name constant for {@code tableMaxNum}.
     */
    public static final String PROPERTYNAME_TABLE_MAX_NUM = "tableMaxNum";
    /**
     * Property name constant for {@code tableTypeName}.
     */
    public static final String PROPERTYNAME_TABLE_TYPE_NAME = "tableTypeName";
    /**
     * Property name constant for {@code lastModTime}.
     */
    public static final String PROPERTYNAME_LAST_MOD_TIME = "lastModTime";
}


