package com.mavenMVC.entity;
// Generated 2017-12-13 22:31:10 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Verifycode generated by hbm2java
 */
@Entity
@Table(name="verifycode"
    ,catalog="farm"
)
public class Verifycode implements java.io.Serializable {


     private Long verifycodeId;
     private Integer verifycodeCode;
     private String verifycodeCellpyone;
     private Long createTime;
     private Long lastModTime;

    public Verifycode() {
    }

    public Verifycode(Integer verifycodeCode, String verifycodeCellpyone, Long createTime, Long lastModTime) {
       this.verifycodeCode = verifycodeCode;
       this.verifycodeCellpyone = verifycodeCellpyone;
       this.createTime = createTime;
       this.lastModTime = lastModTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="VERIFYCODE_ID", unique=true, nullable=false)
    public Long getVerifycodeId() {
        return this.verifycodeId;
    }
    
    public void setVerifycodeId(Long verifycodeId) {
        this.verifycodeId = verifycodeId;
    }
    
    @Column(name="VERIFYCODE_CODE")
    public Integer getVerifycodeCode() {
        return this.verifycodeCode;
    }
    
    public void setVerifycodeCode(Integer verifycodeCode) {
        this.verifycodeCode = verifycodeCode;
    }
    
    @Column(name="VERIFYCODE_CELLPYONE", length=45)
    public String getVerifycodeCellpyone() {
        return this.verifycodeCellpyone;
    }
    
    public void setVerifycodeCellpyone(String verifycodeCellpyone) {
        this.verifycodeCellpyone = verifycodeCellpyone;
    }
    
    @Column(name="CREATE_TIME")
    public Long getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="LAST_MOD_TIME")
    public Long getLastModTime() {
        return this.lastModTime;
    }
    
    public void setLastModTime(Long lastModTime) {
        this.lastModTime = lastModTime;
    }




}


